### ISSUE TITLE
Upgrade fo-dicom to v5.0.0

### ISSUE THREAD

**Issue by rkm** [HicServices/DicomTypeTranslation#106]
We may encounter some breaking issues here.

- v4.0.8:
  > There is the following breaking change from version 4.0.7 to version 4.0.8:
  > - The generated definitions are updated to DICOM Standard 2021b. Now Nema also provides Keywords for the UIDs, these are used in order to be in sync with the DICOM standard. Because of that, some UID keywords have changed.

- v5.0.0
  - [Upgrade from version 4 to version 5](https://github.com/fo-dicom/fo-dicom/wiki/Upgrade-from-version-4-to-version-5)

**Comment by tznind** [comment]
Wow looks like a LOT of breaking changes!

We will need to update all repos at once.  They have even changed the root namespace to `FellowOakDicom` so any runtime linkage with the old dll is going to have a bad time.

> There are now only asynchronous server provider interfaces. All synchronous methods have been replaced by asynchronous.

Probably going to require quite a bit of work and testing to ensure that PACSSource in Rdmp.Dicom still works as expected

Lot of deleted and replaced methods too by the looks of it.

**Comment by jas88** [comment]
Update completed.
